apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: rielu-links2
  namespace: argocd
spec:
  namespace: argocd
  applicationRefs:
    - namePattern: "rielu-links2"
      images:
        - alias: "rielu-links2"
          imageName: "docker.io/rieluinfra/rielu-links2"
          commonUpdateSettings:
            updateStrategy: "latest"